### ISSUE TITLE
Track symbol stays below the route (polyline)

### ISSUE THREAD

**Issue by alexhuynh7** [org-arl/leaflet-tracksymbol2#2]
I showed the track symbol on the map (as a vessel). Somehow, it always stays below the polyline. It looks like there are some issues with zIndex. Does anyone have any idea?
![image](https://github.com/org-arl/leaflet-tracksymbol2/assets/38374492/47479ee6-fef2-4793-a08d-12e390aee35e)

**Comment by ngyewch** [comment]
The polyline was probably added to the map after the track symbol. 

Try adding the track symbol to the map after the polyline. Do take groups into consideration (LayerGroup, FeatureGroup).

**Comment by alexhuynh7** [comment]
@ngyewch I added the track symbol before adding the polylines. I also think the problem is about the layer group but not sure how to check them.

**Comment by alexhuynh7** [comment]
Thank @ngyewch. Your solution worked well.
